In [1]:
import numpy as np 
import torch 

In [2]:
Scalar = torch.tensor(10)
Scalar

tensor(10)

In [3]:
Scalar.ndim

0

In [4]:
Scalar.ndimension

<function Tensor.ndimension>

In [5]:
Scalar.shape

torch.Size([])

In [6]:
Scalar.size()

torch.Size([])

In [7]:
# Vector represents on only single axis 

vector = torch.tensor([7 ,1,2])
vector

tensor([7, 1, 2])

In [8]:
vector.ndim

1

In [9]:
vector.ndimension

<function Tensor.ndimension>

In [10]:
vector.shape

torch.Size([3])

In [11]:
vector.size()

torch.Size([3])

In [12]:
# Matrix is used to build 2d format data 

matrix = torch.tensor([[1,2,3],[10,11,12]])
matrix

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 3])

In [15]:
matrix.size()

torch.Size([2, 3])

In [16]:
individual_values = [i for i in matrix.size()]

individual_values

[2, 3]

In [17]:
matrix[1][2]

tensor(12)

In [18]:
numpy_array = np.array([[1,2,3],[10,11,12]])
numpy_array

array([[ 1,  2,  3],
       [10, 11, 12]])

In [19]:
numpy_array.ndim

2

In [20]:
numpy_array.shape

(2, 3)

In [21]:
numpy_array.size

6

In [22]:
# tensors 

tensors = torch.tensor([[[1,2,3],[10,11,12]]])
tensors

tensor([[[ 1,  2,  3],
         [10, 11, 12]]])

In [23]:
tensors.shape

torch.Size([1, 2, 3])

In [24]:
tensors.size()

torch.Size([1, 2, 3])

In [25]:
tensors[0][1][1]

tensor(11)

In [26]:
tensors.ndim

3

In [27]:
# Random concepts in torch 

In [28]:
torch_random_1d = torch.rand(10)
print(torch_random_1d)
print(torch_random_1d.ndim)


tensor([0.5873, 0.2950, 0.2980, 0.0123, 0.0893, 0.3237, 0.2747, 0.4044, 0.0777,
        0.4283])
1


In [29]:
torch_random_1d = torch.rand(3,5)
print(torch_random_1d)
print(torch_random_1d.ndim)


tensor([[0.0479, 0.8783, 0.1068, 0.7275, 0.4087],
        [0.9803, 0.2393, 0.6564, 0.9610, 0.0924],
        [0.5788, 0.6773, 0.5206, 0.5636, 0.8856]])
2


In [30]:
torch_random_1d = torch.rand(2,3,4)
print(torch_random_1d)
print(torch_random_1d.ndim)


tensor([[[0.7800, 0.2806, 0.7431, 0.3481],
         [0.2476, 0.2107, 0.1318, 0.0030],
         [0.8221, 0.1294, 0.9114, 0.1805]],

        [[0.3175, 0.7547, 0.6349, 0.2384],
         [0.3497, 0.5089, 0.4353, 0.4522],
         [0.7842, 0.6737, 0.8868, 0.0973]]])
3


In [31]:
# Accessing value

torch_random_1d[0][1][1]

tensor(0.2107)

In [32]:
# using randint 

torch_random_randint = torch.randint(3, 10, (2, 2))
torch_random_randint

tensor([[3, 4],
        [9, 6]])

In [33]:
torch_random_randint = torch.randint(20, (2, 2))
torch_random_randint

tensor([[12,  8],
        [ 9,  0]])

In [34]:
# Zero concept 

torch_random_zeros = torch.zeros(3,4,dtype = int)
torch_random_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [35]:
# Ones concept 

torch_random_ones = torch.ones(3,4,dtype = float)
torch_random_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [36]:
# arange function
torch_arange = torch.arange(start = 0 , end = 20 , step = 2)
torch_arange

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
torch_zeros_like = torch.zeros_like(torch_arange)
torch_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
torch_empty = torch.empty(2,3,dtype = int)
torch_empty = torch_empty.fill_(1)
torch_empty

tensor([[1, 1, 1],
        [1, 1, 1]])

In [39]:
torch_ones_like = torch.empty(5,5,dtype = int)
torch_ones_like = torch.ones_like(torch_ones_like)
torch_ones_like

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [40]:
torch.cuda.is_available()

True

In [41]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [42]:
# checking Attributes in tensors

attr = torch.tensor([1,2,11,12] ,device = 'cuda') # device = None means tensors working with cpu 
print('values = {}'.format(attr))
print('dim = {}'.format(attr.ndim))
print('shape = {}'.format(attr.shape))
print('device = {}'.format(attr.device))

values = tensor([ 1,  2, 11, 12], device='cuda:0')
dim = 1
shape = torch.Size([4])
device = cuda:0


# Tensor Operations 

- Addition 
- Multiplication 
- Division 
- Subtraction




In [43]:
tensor_opr = torch.tensor([1,2,3])
tensor_opr + 10

tensor([11, 12, 13])

In [44]:
torch.add(tensor_opr,20)

tensor([21, 22, 23])

In [45]:
a = torch.tensor([1,2,3])
b = torch.tensor([11,12,13])

torch.add(a,b)

tensor([12, 14, 16])

In [46]:
a = torch.tensor([[1,2,3] , [10,11,12]])
b = torch.tensor([[100,200,300] , [500,600,700]])
print(a)
print(b)
torch.add(a,b)


tensor([[ 1,  2,  3],
        [10, 11, 12]])
tensor([[100, 200, 300],
        [500, 600, 700]])


tensor([[101, 202, 303],
        [510, 611, 712]])

In [47]:
# subtraction

tensor_opr = torch.tensor([1,2,3])
tensor_opr - 10

tensor([-9, -8, -7])

In [48]:
tensor_opr = torch.tensor([1,2,3])
torch.sub(tensor_opr,10)

tensor([-9, -8, -7])

In [49]:
# division 

tensor_opr = torch.tensor([1,2,3])
tensor_opr / 10

tensor([0.1000, 0.2000, 0.3000])

In [50]:
tensor_opr = torch.tensor([1,2,3])
torch.div(tensor_opr,10)

tensor([0.1000, 0.2000, 0.3000])

In [51]:
# Multiplication can be done in two days element to element and matrix to matrix 

tensor_opr = torch.tensor([1,2,3])
tensor_opr * 10

tensor([10, 20, 30])

In [52]:
a = torch.tensor([[1,2,3] , [10,11,12]])
print(a)

tensor([[ 1,  2,  3],
        [10, 11, 12]])


In [53]:
a * 10

tensor([[ 10,  20,  30],
        [100, 110, 120]])

In [54]:
a = torch.tensor([[1,2,3] , [10,11,12]])
b = torch.tensor([[2,3] , [5,7] , [2,7]])

print(a)
print()
print(b)
print()

print(torch.matmul(a,b))

tensor([[ 1,  2,  3],
        [10, 11, 12]])

tensor([[2, 3],
        [5, 7],
        [2, 7]])

tensor([[ 18,  38],
        [ 99, 191]])


In [55]:
%%time 

a = torch.tensor([[1,2,3] , [10,11,12]])
b = torch.tensor([[2,3] , [5,7] , [2,7]])

print(a)
print()
print(b)
print()

print(torch.matmul(a,b))

tensor([[ 1,  2,  3],
        [10, 11, 12]])

tensor([[2, 3],
        [5, 7],
        [2, 7]])

tensor([[ 18,  38],
        [ 99, 191]])
Wall time: 2 ms


In [56]:
# Max Min sum and Mean 
# id 
a = torch.arange(1,11)
print(a)
a.max()

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor(10)

In [57]:
torch.max(a)

tensor(10)

In [58]:
torch.min(a)

tensor(1)

In [59]:
torch.sum(a)

tensor(55)

In [60]:
torch.mean(a.type(torch.float32))   # to work with the mean we need to make values as an float dtype 

tensor(5.5000)

In [61]:
# 2d 

b = torch.tensor([[1,2,3] , [10,11,12]])
torch.max(b)

tensor(12)

In [62]:
torch.min(b)

tensor(1)

In [63]:
torch.sum(b)

tensor(39)

In [64]:
print(b)

tensor([[ 1,  2,  3],
        [10, 11, 12]])


In [65]:
torch.mean(b.type(torch.float32))

tensor(6.5000)

In [66]:
# or 

b.type(torch.float64).mean()

tensor(6.5000, dtype=torch.float64)

In [67]:
torch.mean(b.type(torch.float32),dim = 0)  # column wise 

tensor([5.5000, 6.5000, 7.5000])

In [68]:
torch.mean(b.type(torch.float32) , dim = 1)  # row wise 

tensor([ 2., 11.])

In [69]:
print(np.array([[1,2,3] , [10,11,12]]).mean(axis = 0))  # checking with numpy codes 

[5.5 6.5 7.5]


In [70]:
torch.sum(b,dim = 0)


tensor([11, 13, 15])

In [71]:
torch.sum(b,dim=1)

tensor([ 6, 33])

In [72]:
## argmax and argmin will give index positions about value 

a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
torch.argmax(a)  # max value is in 9th index position 

tensor(9)

In [74]:
a[9]

tensor(10)

In [75]:
a.argmin()

tensor(0)

In [76]:
a[0]

tensor(1)

In [77]:
# with 2d 

b

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [78]:
torch.argmax(b,dim = 0) # columns 

tensor([1, 1, 1])

In [79]:
torch.argmax(b,dim=1) # row wise 

tensor([2, 2])

In [80]:
torch.argmin(b,dim=0)  # column wise 

tensor([0, 0, 0])

In [81]:
torch.argmin(b,dim=1) # row wise 

tensor([0, 0])

In [82]:
# Reshaping 

values = torch.arange(1,61).reshape(10,6)
print(values.ndim)
print(values)

2
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]])


In [83]:
values[2][2]

tensor(15)

In [84]:
values = torch.arange(1,61).reshape(5,2,6)
print(values.ndim)
print(values)

3
tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]],

        [[13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35, 36]],

        [[37, 38, 39, 40, 41, 42],
         [43, 44, 45, 46, 47, 48]],

        [[49, 50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59, 60]]])


In [85]:
values[1][1][1]

tensor(20)

In [86]:
values = values.flatten()


In [87]:
values

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60])

In [88]:
values.ndim

1

In [89]:
# Vstack and hstack 

values_a = torch.arange(1,61).reshape(10,6)
values_b = torch.arange(61,121).reshape(10,6)



In [90]:
values_a , values_b

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35, 36],
         [37, 38, 39, 40, 41, 42],
         [43, 44, 45, 46, 47, 48],
         [49, 50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59, 60]]),
 tensor([[ 61,  62,  63,  64,  65,  66],
         [ 67,  68,  69,  70,  71,  72],
         [ 73,  74,  75,  76,  77,  78],
         [ 79,  80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95,  96],
         [ 97,  98,  99, 100, 101, 102],
         [103, 104, 105, 106, 107, 108],
         [109, 110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119, 120]]))

In [91]:
vstack_torch = torch.vstack((values_a,values_b))
vstack_torch

tensor([[  1,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12],
        [ 13,  14,  15,  16,  17,  18],
        [ 19,  20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36],
        [ 37,  38,  39,  40,  41,  42],
        [ 43,  44,  45,  46,  47,  48],
        [ 49,  50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66],
        [ 67,  68,  69,  70,  71,  72],
        [ 73,  74,  75,  76,  77,  78],
        [ 79,  80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96],
        [ 97,  98,  99, 100, 101, 102],
        [103, 104, 105, 106, 107, 108],
        [109, 110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119, 120]])

In [92]:
hstack_torch = torch.hstack((values_a,values_b))
hstack_torch

tensor([[  1,   2,   3,   4,   5,   6,  61,  62,  63,  64,  65,  66],
        [  7,   8,   9,  10,  11,  12,  67,  68,  69,  70,  71,  72],
        [ 13,  14,  15,  16,  17,  18,  73,  74,  75,  76,  77,  78],
        [ 19,  20,  21,  22,  23,  24,  79,  80,  81,  82,  83,  84],
        [ 25,  26,  27,  28,  29,  30,  85,  86,  87,  88,  89,  90],
        [ 31,  32,  33,  34,  35,  36,  91,  92,  93,  94,  95,  96],
        [ 37,  38,  39,  40,  41,  42,  97,  98,  99, 100, 101, 102],
        [ 43,  44,  45,  46,  47,  48, 103, 104, 105, 106, 107, 108],
        [ 49,  50,  51,  52,  53,  54, 109, 110, 111, 112, 113, 114],
        [ 55,  56,  57,  58,  59,  60, 115, 116, 117, 118, 119, 120]])

In [93]:
# Squeeze
# unsqueeze
# Permute 

In [94]:
# Squeeze -> removes all the single dimensions from the selected tensor 
# unsqueeze -> adds single dim to the selected tensor 

In [95]:
values = torch.arange(1,61)
print(f'original dim: {values.shape}')
a = values.reshape(1,-1)
print(f'original dim: {a.shape}')
# removing 1 dimensions value using squeeze
remove_dims = torch.squeeze(a)
print(f'original dim: {remove_dims.shape}')

original dim: torch.Size([60])
original dim: torch.Size([1, 60])
original dim: torch.Size([60])


In [96]:
# unsqueeze
import warnings 
warnings.filterwarnings('ignore')

values = torch.range(1,60)
print(f'original dim: {values.shape}')

#a = values.reshape(1,-1)
#print(f'original dim: {a.shape}')
# Add 1 dimensions value using squeeze
 
add_dims = torch.unsqueeze(values,dim=0)
print(f'original dim: {add_dims.shape}')

original dim: torch.Size([60])
original dim: torch.Size([1, 60])


In [99]:
x = torch.randn(2,3,4)
print(x)
c = torch.permute(x, (1, 2, 0))  # each value represents to its index on original thing 1 is index and its value is 3 

print(c)
print(c.shape)

tensor([[[ 0.6439,  1.2135, -0.7121, -1.1907],
         [-1.0607,  0.3496,  1.4468,  1.6559],
         [ 0.2193,  0.1540,  0.0597, -2.1866]],

        [[-1.1180,  0.9719, -1.5703,  0.2349],
         [-0.1814, -0.6810,  2.3219, -0.8908],
         [-0.7606, -0.3630, -0.7854, -0.5862]]])
tensor([[[ 0.6439, -1.1180],
         [ 1.2135,  0.9719],
         [-0.7121, -1.5703],
         [-1.1907,  0.2349]],

        [[-1.0607, -0.1814],
         [ 0.3496, -0.6810],
         [ 1.4468,  2.3219],
         [ 1.6559, -0.8908]],

        [[ 0.2193, -0.7606],
         [ 0.1540, -0.3630],
         [ 0.0597, -0.7854],
         [-2.1866, -0.5862]]])
torch.Size([3, 4, 2])


### Indexinig concepts using torch

In [100]:
x = torch.arange(1,61).reshape(5,2,6)
x

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]],

        [[13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35, 36]],

        [[37, 38, 39, 40, 41, 42],
         [43, 44, 45, 46, 47, 48]],

        [[49, 50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59, 60]]])

In [101]:
print(x[3][1][1])

tensor(44)


In [102]:
print(x[3][:][:])

tensor([[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48]])


### Pytorch and Numpy 
- numpy to Pytorch 
- Pytorch to numpy 

- Default dtype for numpy was float32
- Default dtype for PyTorch was float64

In [105]:
# numpy to torch 


num_array = np.arange(1.,11.)
print(num_array)
print(num_array.dtype)
convert_tensor = torch.from_numpy(num_array)
print(convert_tensor)
print(convert_tensor.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)
torch.float64


In [106]:
# torch to numpy

torch_array = torch.arange(1.,11.)
print(torch_array)
print(torch_array.dtype)
convert_tensor = torch_array.numpy()
print(convert_tensor)
print(convert_tensor.dtype)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
torch.float32
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float32


### Reproducibility 

- Making random values same for every time using seed module 

In [116]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)
print(a == b)

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644]])
tensor([[False, False, False],
        [False, False, False]])


In [118]:
seed = 42
torch.manual_seed(seed)
a = torch.rand(2,3)
torch.manual_seed(42)
b = torch.rand(2,3)
print(a)
print(b)
print(a == b)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[True, True, True],
        [True, True, True]])


- with numpy 

In [120]:
a1 = np.random.rand(3,2)
b1 = np.random.rand(3,2)
print(a1)
print(b1)
print(a1 == b1)

[[0.40705257 0.72824331]
 [0.26129222 0.58916409]
 [0.18465088 0.97018141]]
[[0.38292185 0.31215803]
 [0.12539772 0.93936589]
 [0.96967379 0.73503137]]
[[False False]
 [False False]
 [False False]]


In [124]:
seed = 42
np.random.seed(seed)
a1 = np.random.rand(3,2)
np.random.seed(seed)
b1 = np.random.rand(3,2)
print(a1)
print(b1)
print(a1 == b1)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
[[ True  True]
 [ True  True]
 [ True  True]]


### checking for GPU access for PyTorch 

In [125]:
torch.cuda.is_available()

True

### setup device agnostic code 

In [141]:
d = 'cuda' if torch.cuda.is_available() else 'cpu'
d

'cuda'

### Count the number of devices 

In [127]:
torch.cuda.device_count()

1

### Creating tensors on gpu 

In [142]:
# default tensors will be work on cpu 
tensor_cpu = torch.tensor([1,2,3,4])
print(tensor_cpu)

tensor([1, 2, 3, 4])


In [143]:
print(tensor_cpu.device)

cpu


In [144]:
# Making Tensors on gpu 

tensor_cpu = torch.tensor([1,2,3,4])
tensor_gpu = tensor_cpu.to(d)  # converting cpu to gpu 
print(tensor_gpu.device)

cuda:0


In [145]:
## convert cpu created tensors into numpy 

tensor_cpu = torch.tensor([1,2,3,4])
num_array = tensor_cpu.numpy()
num_array

array([1, 2, 3, 4], dtype=int64)

In [148]:
## convert gpu created tensors into numpy 
# numpy will not work with gpu so first convert gpu tensors into cpu and from cpu to numpy 


tensor_gpu = torch.tensor([1,2,3,4],device = 'cuda')

num_array1 = tensor_gpu.numpy()
num_array1

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [149]:
## convert gpu created tensors into numpy 
# numpy will not work with gpu so first convert gpu tensors into cpu and from cpu to numpy 


tensor_gpu = torch.tensor([1,2,3,4],device = 'cuda')
num_array = tensor_gpu.cpu()
num_array1 = num_array.numpy()
num_array1

array([1, 2, 3, 4], dtype=int64)